#!/bin/sh

# Run static analysis
npx playwright test

# Check the exit code of the lint command
if [ $? -ne 0 ]; then
  echo "Testing failed. Please fix the errors before committing."
  exit 1
fi

# If we get here, linting passed
echo "Testing passed. Proceeding with the push."
exit 0
