language: "ja"
early_access: false
reviews:
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  path_instructions:
    - path: "**/*.{ts,tsx,scss}"
      instructions: |
        "Use 2 spaces for indentation.
        Follow the Boy Scout Rule: Leave the code cleaner than you found it.
        Follow YAGNI (You Aren't Gonna Need It): Don't implement functionality until it's needed.
        Follow DRY (Don't Repeat Yourself): Avoid duplicating code by extracting reusable logic into functions.
        Follow KISS (Keep It Simple, Stupid): Write simple, straightforward code.
        Detect and propose corrections for typos.
        Avoid using deprecated or obsolete features as listed on MDN: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features."
    - path: "**/*.{ts,tsx,js}"
      instructions: |
        "Ensure compliance with the Google JavaScript Style Guide and highlight any deviations.
        Follow React best practices when writing code.
        Use camelCase for property names and apply PropTypes where necessary.
        Follow the official React guidelines for hook usage.
        Avoid inline styles.
        Use 'let' or 'const' instead of 'var'. Highlight any usage of 'var'.
        Implement performance optimizations such as memoization and render optimization where appropriate.
        Use React.memo() for functional components and PureComponent for class components to prevent unnecessary re-renders.
        Implement code splitting and lazy loading for better performance.
        Be cautious of potential security vulnerabilities, especially cross-site scripting (XSS).
        Sanitize user inputs and avoid using dangerouslySetInnerHTML."
    - path: "**/*.tsx"
      instructions: |
        "Use semantic HTML elements such to improve the structure and accessibility of the code.
        Implement WAI-ARIA attributes to enhance accessibility.
        Ensure proper keyboard navigation support for all interactive elements.
        Use aria-label or aria-labelledby for elements without visible text.
        Implement focus management for modals and other dynamic content."
    - path: "**/*.scss"
      instructions: |
        "Use BEM naming conventions for CSS selectors, and use kebab-case (lowercase and hyphens) for word separators.
        Use lowercase for color codes.
        Limit nesting to a maximum of 3 levels deep to maintain readability.
        Use variables for colors, fonts, and other repeated values.
        Group related styles and use comments to separate sections.
        Avoid using !important unless absolutely necessary.
        Use mixins and functions to promote code reuse and maintainability."
    - path: "tests/*"
      instructions: |
        "Evaluate whether the test code adheres to best practices for the testing framework in use.
        Ensure that test descriptions are detailed enough to clarify the purpose of each test.
        Use appropriate assertions and matchers.
        Implement test coverage for critical paths and edge cases.
        Keep tests independent and avoid shared state between tests."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "dev"
      - "feature/.*"
      - "hotfix/.*"
chat:
  auto_reply: true
